const Screens = {
  singIn: '/',
  'sign-up': '/sign-up',
  'forgot-password': '/forgot-password',
  TOS: '/terms-of-use',
  privacyPolicy: '/privacy-policy',
  //
  home: '/home',
  'food-review': '/food-review',
  search: '/search',
  favourites: '/favourites',
  settings: '/settings',
  cart: '/cart',
  'select-address': '/place-order/select-address',
  'create-address': '/place-order/create-address',
  'select-card': '/place-order/select-card',
  'create-card': '/place-order/create-card',
  'show-delivery': '/place-order/show-delivery',
  drawerone: '/drawer/one',
  drawertwo: '/drawer/two',
  tabsone: '/tabs/one',
  tabstwo: '/tabs/two',
  'shared-one': '/shared/one',
  'shared-two': '/shared/two',
  'landing-first': '/landing/first',
  'landing-second': '/landing/second',
  'landing-third': '/landing/third',
}

export default Screens
